// Copyright 2023 Google LLC
 //
 // This source code is licensed under the BSD-style license found in the
 // LICENSE file in the root directory of this source tree.
 // Arguments are:
 // XNN_GEMM(arch_flags, fn_name, k_block, is_pipelined, mr, nr, kr, sr, mr_packed, unsigned_inputs, datatype, params_type, init_fn, pack_fn, pack_stride)
 
 
#if XNN_ARCH_ARM
XNN_GEMM(xnn_arch_arm_v6, xnn_qu8_igemm_minmax_fp32_ukernel_1x1c4__armsimd32, 4, true, 1, 1, 4, 1, 1, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_armsimd32_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(xnn_arch_arm_v6, xnn_qu8_igemm_minmax_fp32_ukernel_1x2c4__armsimd32, 4, true, 1, 2, 4, 1, 1, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_armsimd32_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(xnn_arch_arm_v6, xnn_qu8_igemm_minmax_fp32_ukernel_2x1c4__armsimd32, 4, true, 2, 1, 4, 1, 2, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_armsimd32_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(xnn_arch_arm_v6, xnn_qu8_igemm_minmax_fp32_ukernel_2x2c4__armsimd32, 4, true, 2, 2, 4, 1, 2, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_armsimd32_params, xnn_pack_qu8_conv_goki_w, NULL)
#endif  // XNN_ARCH_ARM

#if XNN_ARCH_ARM || XNN_ARCH_ARM64
XNN_GEMM(xnn_arch_arm_neon, xnn_qu8_igemm_minmax_fp32_ukernel_1x8__neon_mlal_lane, 8, true, 1, 8, 1, 1, 1, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_neon_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(xnn_arch_arm_neon, xnn_qu8_igemm_minmax_fp32_ukernel_1x16__neon_mlal_lane, 8, true, 1, 16, 1, 1, 1, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_neon_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(xnn_arch_arm_neon_v8, xnn_qu8_igemm_minmax_fp32_ukernel_1x16__neonv8_mlal_lane, 8, true, 1, 16, 1, 1, 1, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_neonv8_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(xnn_arch_arm_neon, xnn_qu8_igemm_minmax_fp32_ukernel_4x8__neon_mlal_lane, 8, true, 4, 8, 1, 1, 4, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_neon_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(xnn_arch_arm_neon, xnn_qu8_igemm_minmax_fp32_ukernel_4x16__neon_mlal_lane, 8, true, 4, 16, 1, 1, 4, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_neon_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(xnn_arch_arm_neon_v8, xnn_qu8_igemm_minmax_fp32_ukernel_4x16__neonv8_mlal_lane, 8, true, 4, 16, 1, 1, 4, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_neonv8_params, xnn_pack_qu8_conv_goki_w, NULL)
#endif  // XNN_ARCH_ARM || XNN_ARCH_ARM64

#if XNN_ARCH_X86 || XNN_ARCH_X86_64
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_1x4c2__sse2_ld64, 8, true, 1, 4, 2, 1, 1, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(xnn_arch_x86_sse4_1, xnn_qu8_igemm_minmax_fp32_ukernel_1x4c2__sse41_ld64, 8, true, 1, 4, 2, 1, 1, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_2x4c2__sse2_ld64, 8, true, 2, 4, 2, 1, 2, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(xnn_arch_x86_sse4_1, xnn_qu8_igemm_minmax_fp32_ukernel_2x4c2__sse41_ld64, 8, true, 2, 4, 2, 1, 2, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_3x4c2__sse2_ld64, 8, true, 3, 4, 2, 1, 3, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(xnn_arch_x86_sse4_1, xnn_qu8_igemm_minmax_fp32_ukernel_3x4c2__sse41_ld64, 8, true, 3, 4, 2, 1, 3, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_4x4c2__sse2_ld64, 8, true, 4, 4, 2, 1, 4, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(xnn_arch_x86_sse4_1, xnn_qu8_igemm_minmax_fp32_ukernel_4x4c2__sse41_ld64, 8, true, 4, 4, 2, 1, 4, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_1x4c2__sse2_ld128, 8, true, 1, 4, 2, 1, 1, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(xnn_arch_x86_sse4_1, xnn_qu8_igemm_minmax_fp32_ukernel_1x4c2__sse41_ld128, 8, true, 1, 4, 2, 1, 1, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_2x4c2__sse2_ld128, 8, true, 2, 4, 2, 1, 2, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(xnn_arch_x86_sse4_1, xnn_qu8_igemm_minmax_fp32_ukernel_2x4c2__sse41_ld128, 8, true, 2, 4, 2, 1, 2, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_3x4c2__sse2_ld128, 8, true, 3, 4, 2, 1, 3, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(xnn_arch_x86_sse4_1, xnn_qu8_igemm_minmax_fp32_ukernel_3x4c2__sse41_ld128, 8, true, 3, 4, 2, 1, 3, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_4x4c2__sse2_ld128, 8, true, 4, 4, 2, 1, 4, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(xnn_arch_x86_sse4_1, xnn_qu8_igemm_minmax_fp32_ukernel_4x4c2__sse41_ld128, 8, true, 4, 4, 2, 1, 4, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_1x4c2s4__sse2_ld64, 8, true, 1, 4, 2, 4, 1, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(xnn_arch_x86_sse4_1, xnn_qu8_igemm_minmax_fp32_ukernel_1x4c2s4__sse41_ld64, 8, true, 1, 4, 2, 4, 1, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_2x4c2s4__sse2_ld64, 8, true, 2, 4, 2, 4, 2, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(xnn_arch_x86_sse4_1, xnn_qu8_igemm_minmax_fp32_ukernel_2x4c2s4__sse41_ld64, 8, true, 2, 4, 2, 4, 2, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_3x4c2s4__sse2_ld64, 8, true, 3, 4, 2, 4, 3, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(xnn_arch_x86_sse4_1, xnn_qu8_igemm_minmax_fp32_ukernel_3x4c2s4__sse41_ld64, 8, true, 3, 4, 2, 4, 3, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_4x4c2s4__sse2_ld64, 8, true, 4, 4, 2, 4, 4, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(xnn_arch_x86_sse4_1, xnn_qu8_igemm_minmax_fp32_ukernel_4x4c2s4__sse41_ld64, 8, true, 4, 4, 2, 4, 4, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_1x4c2s4__sse2_ld128, 8, true, 1, 4, 2, 4, 1, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(xnn_arch_x86_sse4_1, xnn_qu8_igemm_minmax_fp32_ukernel_1x4c2s4__sse41_ld128, 8, true, 1, 4, 2, 4, 1, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_2x4c2s4__sse2_ld128, 8, true, 2, 4, 2, 4, 2, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(xnn_arch_x86_sse4_1, xnn_qu8_igemm_minmax_fp32_ukernel_2x4c2s4__sse41_ld128, 8, true, 2, 4, 2, 4, 2, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_3x4c2s4__sse2_ld128, 8, true, 3, 4, 2, 4, 3, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(xnn_arch_x86_sse4_1, xnn_qu8_igemm_minmax_fp32_ukernel_3x4c2s4__sse41_ld128, 8, true, 3, 4, 2, 4, 3, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_4x4c2s4__sse2_ld128, 8, true, 4, 4, 2, 4, 4, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(xnn_arch_x86_sse4_1, xnn_qu8_igemm_minmax_fp32_ukernel_4x4c2s4__sse41_ld128, 8, true, 4, 4, 2, 4, 4, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_1x4c8__sse2_ld64, 8, true, 1, 4, 8, 1, 1, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(xnn_arch_x86_sse4_1, xnn_qu8_igemm_minmax_fp32_ukernel_1x4c8__sse41_ld64, 8, true, 1, 4, 8, 1, 1, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_2x4c8__sse2_ld64, 8, true, 2, 4, 8, 1, 2, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(xnn_arch_x86_sse4_1, xnn_qu8_igemm_minmax_fp32_ukernel_2x4c8__sse41_ld64, 8, true, 2, 4, 8, 1, 2, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_3x4c8__sse2_ld64, 8, true, 3, 4, 8, 1, 3, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(xnn_arch_x86_sse4_1, xnn_qu8_igemm_minmax_fp32_ukernel_3x4c8__sse41_ld64, 8, true, 3, 4, 8, 1, 3, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_1x4c8__sse2_ld128, 8, true, 1, 4, 8, 1, 1, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(xnn_arch_x86_sse4_1, xnn_qu8_igemm_minmax_fp32_ukernel_1x4c8__sse41_ld128, 8, true, 1, 4, 8, 1, 1, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_2x4c8__sse2_ld128, 8, true, 2, 4, 8, 1, 2, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(xnn_arch_x86_sse4_1, xnn_qu8_igemm_minmax_fp32_ukernel_2x4c8__sse41_ld128, 8, true, 2, 4, 8, 1, 2, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_3x4c8__sse2_ld128, 8, true, 3, 4, 8, 1, 3, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(xnn_arch_x86_sse4_1, xnn_qu8_igemm_minmax_fp32_ukernel_3x4c8__sse41_ld128, 8, true, 3, 4, 8, 1, 3, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(xnn_arch_x86_avx, xnn_qu8_igemm_minmax_fp32_ukernel_1x4c2__avx_ld64, 8, true, 1, 4, 2, 1, 1, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(xnn_arch_x86_avx, xnn_qu8_igemm_minmax_fp32_ukernel_2x4c2__avx_ld64, 8, true, 2, 4, 2, 1, 2, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(xnn_arch_x86_avx, xnn_qu8_igemm_minmax_fp32_ukernel_3x4c2__avx_ld64, 8, true, 3, 4, 2, 1, 3, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(xnn_arch_x86_avx, xnn_qu8_igemm_minmax_fp32_ukernel_4x4c2__avx_ld64, 8, true, 4, 4, 2, 1, 4, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(xnn_arch_x86_avx, xnn_qu8_igemm_minmax_fp32_ukernel_1x4c2__avx_ld128, 8, true, 1, 4, 2, 1, 1, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(xnn_arch_x86_avx, xnn_qu8_igemm_minmax_fp32_ukernel_2x4c2__avx_ld128, 8, true, 2, 4, 2, 1, 2, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(xnn_arch_x86_avx, xnn_qu8_igemm_minmax_fp32_ukernel_3x4c2__avx_ld128, 8, true, 3, 4, 2, 1, 3, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(xnn_arch_x86_avx, xnn_qu8_igemm_minmax_fp32_ukernel_4x4c2__avx_ld128, 8, true, 4, 4, 2, 1, 4, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(xnn_arch_x86_avx, xnn_qu8_igemm_minmax_fp32_ukernel_1x4c2s4__avx_ld64, 8, true, 1, 4, 2, 4, 1, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(xnn_arch_x86_avx, xnn_qu8_igemm_minmax_fp32_ukernel_2x4c2s4__avx_ld64, 8, true, 2, 4, 2, 4, 2, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(xnn_arch_x86_avx, xnn_qu8_igemm_minmax_fp32_ukernel_3x4c2s4__avx_ld64, 8, true, 3, 4, 2, 4, 3, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(xnn_arch_x86_avx, xnn_qu8_igemm_minmax_fp32_ukernel_4x4c2s4__avx_ld64, 8, true, 4, 4, 2, 4, 4, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(xnn_arch_x86_avx, xnn_qu8_igemm_minmax_fp32_ukernel_1x4c2s4__avx_ld128, 8, true, 1, 4, 2, 4, 1, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(xnn_arch_x86_avx, xnn_qu8_igemm_minmax_fp32_ukernel_2x4c2s4__avx_ld128, 8, true, 2, 4, 2, 4, 2, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(xnn_arch_x86_avx, xnn_qu8_igemm_minmax_fp32_ukernel_3x4c2s4__avx_ld128, 8, true, 3, 4, 2, 4, 3, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(xnn_arch_x86_avx, xnn_qu8_igemm_minmax_fp32_ukernel_4x4c2s4__avx_ld128, 8, true, 4, 4, 2, 4, 4, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(xnn_arch_x86_avx, xnn_qu8_igemm_minmax_fp32_ukernel_1x4c8__avx_ld64, 8, true, 1, 4, 8, 1, 1, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(xnn_arch_x86_avx, xnn_qu8_igemm_minmax_fp32_ukernel_2x4c8__avx_ld64, 8, true, 2, 4, 8, 1, 2, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(xnn_arch_x86_avx, xnn_qu8_igemm_minmax_fp32_ukernel_3x4c8__avx_ld64, 8, true, 3, 4, 8, 1, 3, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(xnn_arch_x86_avx, xnn_qu8_igemm_minmax_fp32_ukernel_1x4c8__avx_ld128, 8, true, 1, 4, 8, 1, 1, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(xnn_arch_x86_avx, xnn_qu8_igemm_minmax_fp32_ukernel_2x4c8__avx_ld128, 8, true, 2, 4, 8, 1, 2, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(xnn_arch_x86_avx, xnn_qu8_igemm_minmax_fp32_ukernel_3x4c8__avx_ld128, 8, true, 3, 4, 8, 1, 3, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(xnn_arch_x86_avx2, xnn_qu8_igemm_minmax_fp32_ukernel_1x8c8__avx2, 8, true, 1, 8, 8, 1, 1, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(xnn_arch_x86_avx2, xnn_qu8_igemm_minmax_fp32_ukernel_2x8c8__avx2, 8, true, 2, 8, 8, 1, 2, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(xnn_arch_x86_avx2, xnn_qu8_igemm_minmax_fp32_ukernel_3x8c8__avx2, 8, true, 3, 8, 8, 1, 3, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(xnn_arch_x86_avx2, xnn_qu8_igemm_minmax_fp32_ukernel_4x8c8__avx2, 8, true, 4, 8, 8, 1, 4, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
#endif  // XNN_ARCH_X86 || XNN_ARCH_X86_64

#if XNN_ENABLE_AVX256SKX && (XNN_ARCH_X86 || XNN_ARCH_X86_64)
XNN_GEMM(xnn_arch_x86_avx256skx, xnn_qu8_igemm_minmax_fp32_ukernel_1x8c8__avx256skx, 8, true, 1, 8, 8, 1, 1, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
#endif  // XNN_ENABLE_AVX256SKX && (XNN_ARCH_X86 || XNN_ARCH_X86_64)

#if XNN_ENABLE_AVX512SKX && (XNN_ARCH_X86 || XNN_ARCH_X86_64)
XNN_GEMM(xnn_arch_x86_avx512skx, xnn_qu8_igemm_minmax_fp32_ukernel_1x16c8__avx512skx, 8, true, 1, 16, 8, 1, 1, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(xnn_arch_x86_avx512skx, xnn_qu8_igemm_minmax_fp32_ukernel_5x16c8__avx512skx, 8, true, 5, 16, 8, 1, 5, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(xnn_arch_x86_avx512skx, xnn_qu8_igemm_minmax_fp32_ukernel_7x16c8__avx512skx, 8, true, 7, 16, 8, 1, 7, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(xnn_arch_x86_avx512skx, xnn_qu8_igemm_minmax_fp32_ukernel_8x16c8__avx512skx, 8, true, 8, 16, 8, 1, 8, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(xnn_arch_x86_avx512skx, xnn_qu8_igemm_minmax_fp32_ukernel_1x16c8__avx512skx_prfm, 8, true, 1, 16, 8, 1, 1, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(xnn_arch_x86_avx512skx, xnn_qu8_igemm_minmax_fp32_ukernel_5x16c8__avx512skx_prfm, 8, true, 5, 16, 8, 1, 5, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(xnn_arch_x86_avx512skx, xnn_qu8_igemm_minmax_fp32_ukernel_7x16c8__avx512skx_prfm, 8, true, 7, 16, 8, 1, 7, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(xnn_arch_x86_avx512skx, xnn_qu8_igemm_minmax_fp32_ukernel_8x16c8__avx512skx_prfm, 8, true, 8, 16, 8, 1, 8, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
#endif  // XNN_ENABLE_AVX512SKX && (XNN_ARCH_X86 || XNN_ARCH_X86_64)

#if XNN_ARCH_WASMSIMD || XNN_ARCH_WASMRELAXEDSIMD
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_1x4c2__wasmsimd_dot16x2_ld64, 8, true, 1, 4, 2, 1, 1, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_1x4c2__wasmsimd_dot16x2_ld128, 8, true, 1, 4, 2, 1, 1, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_1x4c2s4__wasmsimd_dot16x2_ld64, 8, true, 1, 4, 2, 4, 1, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_1x4c2s4__wasmsimd_dot16x2_ld128, 8, true, 1, 4, 2, 4, 1, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_1x4c8__wasmsimd_dot16x2_ld64, 8, true, 1, 4, 8, 1, 1, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_1x4c8__wasmsimd_dot16x2_ld128, 8, true, 1, 4, 8, 1, 1, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_2x4c2__wasmsimd_dot16x2_ld64, 8, true, 2, 4, 2, 1, 2, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_2x4c2__wasmsimd_dot16x2_ld128, 8, true, 2, 4, 2, 1, 2, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_2x4c2s4__wasmsimd_dot16x2_ld64, 8, true, 2, 4, 2, 4, 2, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_2x4c2s4__wasmsimd_dot16x2_ld128, 8, true, 2, 4, 2, 4, 2, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_2x4c8__wasmsimd_dot16x2_ld64, 8, true, 2, 4, 8, 1, 2, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_2x4c8__wasmsimd_dot16x2_ld128, 8, true, 2, 4, 8, 1, 2, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_3x4c2__wasmsimd_dot16x2_ld64, 8, true, 3, 4, 2, 1, 3, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_3x4c2__wasmsimd_dot16x2_ld128, 8, true, 3, 4, 2, 1, 3, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_3x4c2s4__wasmsimd_dot16x2_ld64, 8, true, 3, 4, 2, 4, 3, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_3x4c2s4__wasmsimd_dot16x2_ld128, 8, true, 3, 4, 2, 4, 3, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_3x4c8__wasmsimd_dot16x2_ld64, 8, true, 3, 4, 8, 1, 3, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_3x4c8__wasmsimd_dot16x2_ld128, 8, true, 3, 4, 8, 1, 3, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_4x4c2__wasmsimd_dot16x2_ld64, 8, true, 4, 4, 2, 1, 4, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_4x4c2__wasmsimd_dot16x2_ld128, 8, true, 4, 4, 2, 1, 4, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_4x4c2s4__wasmsimd_dot16x2_ld64, 8, true, 4, 4, 2, 4, 4, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_4x4c2s4__wasmsimd_dot16x2_ld128, 8, true, 4, 4, 2, 4, 4, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_4x4c8__wasmsimd_dot16x2_ld64, 8, true, 4, 4, 8, 1, 4, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_4x4c8__wasmsimd_dot16x2_ld128, 8, true, 4, 4, 8, 1, 4, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
#endif  // XNN_ARCH_WASMSIMD || XNN_ARCH_WASMRELAXEDSIMD

#if XNN_ARCH_WASM || XNN_ARCH_WASMSIMD || XNN_ARCH_WASMRELAXEDSIMD
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_1x2__wasm_fmagic, 1, true, 1, 2, 1, 1, 1, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_1x4__wasm_fmagic, 1, true, 1, 4, 1, 1, 1, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_2x2__wasm_fmagic, 1, true, 2, 2, 1, 1, 2, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_2x4__wasm_fmagic, 1, true, 2, 4, 1, 1, 2, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_3x2__wasm_fmagic, 1, true, 3, 2, 1, 1, 3, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_3x4__wasm_fmagic, 1, true, 3, 4, 1, 1, 3, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_4x2__wasm_fmagic, 1, true, 4, 2, 1, 1, 4, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_4x4__wasm_fmagic, 1, true, 4, 4, 1, 1, 4, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
#endif  // XNN_ARCH_WASM || XNN_ARCH_WASMSIMD || XNN_ARCH_WASMRELAXEDSIMD

XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_1x2__scalar_fmagic, 1, true, 1, 2, 1, 1, 1, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_1x2__scalar_imagic, 1, true, 1, 2, 1, 1, 1, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_1x2__scalar_lrintf, 1, true, 1, 2, 1, 1, 1, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_1x4__scalar_fmagic, 1, true, 1, 4, 1, 1, 1, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_1x4__scalar_imagic, 1, true, 1, 4, 1, 1, 1, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_1x4__scalar_lrintf, 1, true, 1, 4, 1, 1, 1, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_2x2__scalar_fmagic, 1, true, 2, 2, 1, 1, 2, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_2x2__scalar_imagic, 1, true, 2, 2, 1, 1, 2, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_2x2__scalar_lrintf, 1, true, 2, 2, 1, 1, 2, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_2x4__scalar_fmagic, 1, true, 2, 4, 1, 1, 2, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_2x4__scalar_imagic, 1, true, 2, 4, 1, 1, 2, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_2x4__scalar_lrintf, 1, true, 2, 4, 1, 1, 2, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_3x2__scalar_fmagic, 1, true, 3, 2, 1, 1, 3, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_3x2__scalar_imagic, 1, true, 3, 2, 1, 1, 3, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_3x2__scalar_lrintf, 1, true, 3, 2, 1, 1, 3, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_3x4__scalar_fmagic, 1, true, 3, 4, 1, 1, 3, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_3x4__scalar_imagic, 1, true, 3, 4, 1, 1, 3, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_3x4__scalar_lrintf, 1, true, 3, 4, 1, 1, 3, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_4x2__scalar_fmagic, 1, true, 4, 2, 1, 1, 4, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_4x2__scalar_imagic, 1, true, 4, 2, 1, 1, 4, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_4x2__scalar_lrintf, 1, true, 4, 2, 1, 1, 4, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_4x4__scalar_fmagic, 1, true, 4, 4, 1, 1, 4, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_4x4__scalar_imagic, 1, true, 4, 4, 1, 1, 4, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
XNN_GEMM(0, xnn_qu8_igemm_minmax_fp32_ukernel_4x4__scalar_lrintf, 1, true, 4, 4, 1, 1, 4, false, uint8_t, union xnn_qu8_conv_minmax_params, xnn_init_qu8_conv_minmax_fp32_scalar_params, xnn_pack_qu8_conv_goki_w, NULL)
