// Copyright 2023 Google LLC
//
// This source code is licensed under the BSD-style license found in the
// LICENSE file in the root directory of this source tree.
// Arguments are:
// XNN_GEMM_MINMAX(arch_flags, fn_name, k_block, is_pipelined, mr, nr, kr, sr, mr_packed, is_igemm, datatype, params_type, init_fn, pack_fn)

#if XNN_ARCH_ARM && XNN_ENABLE_ASSEMBLY
XNN_GEMM(XNN_ARCH_ARM, xnn_f32_gemm_minmax_ukernel_1x8__asm_aarch32_neon_cortex_a53_prfm, 2 false, 1, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM, xnn_f32_gemm_minmax_ukernel_4x8__asm_aarch32_neon_cortex_a7, 2, false, 4, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM, xnn_f32_gemm_minmax_ukernel_4x8__asm_aarch32_neon_cortex_a53_prfm, 4, true, 4, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM, xnn_f32_gemm_minmax_ukernel_4x8__asm_aarch32_neon_cortex_a55, 4, true, 4, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM, xnn_f32_gemm_minmax_ukernel_4x8__asm_aarch32_neon_cortex_a75, 4, true, 4, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM, xnn_f32_gemm_minmax_ukernel_4x8__asm_aarch32_neon_cortex_a75_prfm, 4, true, 4, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM, xnn_f32_gemm_minmax_ukernel_1x8__asm_aarch32_neon_cortex_a53, 2, false, 1, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM, xnn_f32_gemm_minmax_ukernel_4x4__asm_aarch32_vfp_ld64, 2, false, 4, 4, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM, xnn_f32_gemm_minmax_ukernel_4x8__asm_aarch32_neon_cortex_a53, 4, true, 4, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM, xnn_f32_gemm_minmax_ukernel_4x8__asm_aarch32_neon_ld64, 2, false, 4, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
#endif  // XNN_ARCH_ARM && XNN_ENABLE_ASSEMBLY

#if XNN_ARCH_ARM64 && XNN_ENABLE_ASSEMBLY
XNN_GEMM(XNN_ARCH_ARM64, xnn_f32_gemm_minmax_ukernel_1x8__asm_aarch64_neon_ld128_acc2, 4, false, 1, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM64, xnn_f32_gemm_minmax_ukernel_1x8__asm_aarch64_neonfma_cortex_a53, 8, true, 1, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM64, xnn_f32_gemm_minmax_ukernel_1x8__asm_aarch64_neonfma_ld64, 2, false, 1, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM64, xnn_f32_gemm_minmax_ukernel_1x8__asm_aarch64_neonfma_ld64_acc2_prfm, 2, false, 1, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM64, xnn_f32_gemm_minmax_ukernel_1x8__asm_aarch64_neonfma_ld64_acc4, 4, false, 1, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM64, xnn_f32_gemm_minmax_ukernel_1x8__asm_aarch64_neonfma_ld64_prfm, 2, false, 1, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM64, xnn_f32_gemm_minmax_ukernel_1x8__asm_aarch64_neonfma_ld128, 4, false, 1, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM64, xnn_f32_gemm_minmax_ukernel_1x8__asm_aarch64_neonfma_ld128_acc2, 4, false, 1, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM64, xnn_f32_gemm_minmax_ukernel_1x8__asm_aarch64_neonfma_ld128_acc4_prfm, 4, false, 1, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM64, xnn_f32_gemm_minmax_ukernel_1x12__asm_aarch64_neonfma_cortex_a53, 4, true, 1, 12, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM64, xnn_f32_gemm_minmax_ukernel_4x1__asm_aarch64_neonfma_ld64, 2, false, 4, 1, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM64, xnn_f32_gemm_minmax_ukernel_4x2__asm_aarch64_neonfma_cortex_a75, 8, false, 4, 2, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM64, xnn_f32_gemm_minmax_ukernel_4x2__asm_aarch64_neonfma_cortex_a75_prfm, 8, false, 4, 2, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM64, xnn_f32_gemm_minmax_ukernel_4x2__asm_aarch64_neonfma_ld128, 4, false, 4, 2, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM64, xnn_f32_gemm_minmax_ukernel_4x8__asm_aarch64_neonfma_cortex_a53, 4, true, 4, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM64, xnn_f32_gemm_minmax_ukernel_4x8__asm_aarch64_neonfma_ld128, 4, false, 4, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM64, xnn_f32_gemm_minmax_ukernel_4x12__asm_aarch64_neonfma_cortex_a53, 4, true, 4, 12, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM64, xnn_f32_gemm_minmax_ukernel_5x8__asm_aarch64_neonfma_cortex_a75_prfm, 8, true, 5, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM64, xnn_f32_gemm_minmax_ukernel_6x8__asm_aarch64_neonfma_cortex_a53_prfm, 4, ture, 6, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM64, xnn_f32_gemm_minmax_ukernel_6x8__asm_aarch64_neonfma_cortex_a55, 4, true, 6, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM64, xnn_f32_gemm_minmax_ukernel_6x8__asm_aarch64_neonfma_cortex_a75, 8, true, 6, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM64, xnn_f32_gemm_minmax_ukernel_6x8__asm_aarch64_neonfma_cortex_a75_prfm, 8, true, 6, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM64, xnn_f32_gemm_minmax_ukernel_6x8__asm_aarch64_neonfma_ld128, 4, false, 6, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM64, xnn_f32_gemm_minmax_ukernel_1x8__asm_aarch64_neon_ld128_acc2_prfm, 4, false, 1, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM64, xnn_f32_gemm_minmax_ukernel_1x8__asm_aarch64_neonfma_cortex_a53_prfm, 8, true, 1, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM64, xnn_f32_gemm_minmax_ukernel_1x8__asm_aarch64_neonfma_cortex_a75, 8, true, 16, 1, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM64, xnn_f32_gemm_minmax_ukernel_1x8__asm_aarch64_neonfma_cortex_a75_prfm, 8, true, 1, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM64, xnn_f32_gemm_minmax_ukernel_1x8__asm_aarch64_neonfma_ld64_acc2, 2, false, 1, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM64, xnn_f32_gemm_minmax_ukernel_1x8__asm_aarch64_neonfma_ld64_acc4_prfm, 4, false, 1, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM64, xnn_f32_gemm_minmax_ukernel_1x8__asm_aarch64_neonfma_ld128_acc2_prfm, 4, false, 1, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM64, xnn_f32_gemm_minmax_ukernel_1x8__asm_aarch64_neonfma_ld128_acc4, 4, false, 1, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM64, xnn_f32_gemm_minmax_ukernel_1x8__asm_aarch64_neonfma_ld128_prfm, 4, false, 1, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM64, xnn_f32_gemm_minmax_ukernel_4x1__asm_aarch64_neonfma_ld128, 4, false, 4, 1, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM64, xnn_f32_gemm_minmax_ukernel_4x2__asm_aarch64_neonfma_ld64, 2, false, 4, 2, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM64, xnn_f32_gemm_minmax_ukernel_4x8__asm_aarch64_neonfma_cortex_a53_prfm, 4, true, 4, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM64, xnn_f32_gemm_minmax_ukernel_4x8__asm_aarch64_neonfma_cortex_a55, 4, true, 4, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM64, xnn_f32_gemm_minmax_ukernel_4x8__asm_aarch64_neonfma_cortex_a75, 8, true, 4, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM64, xnn_f32_gemm_minmax_ukernel_4x8__asm_aarch64_neonfma_cortex_a75_prfm, 8, true, 4, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM64, xnn_f32_gemm_minmax_ukernel_4x8__asm_aarch64_neonfma_ld64, 2, false, 4, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM64, xnn_f32_gemm_minmax_ukernel_5x8__asm_aarch64_neonfma_cortex_a75, 8, true, 16, 5, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM64, xnn_f32_gemm_minmax_ukernel_6x8__asm_aarch64_neonfma_cortex_a53, 4, true, 6, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM64, xnn_f32_gemm_minmax_ukernel_6x8__asm_aarch64_neonfma_cortex_a73, 8, true, 6, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM64, xnn_f32_gemm_minmax_ukernel_6x8__asm_aarch64_neonfma_ld64, 2, false, 6, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
#endif  // XNN_ARCH_ARM64 && XNN_ENABLE_ASSEMBLY

#if XNN_ARCH_ARM || XNN_ARCH_ARM64
XNN_GEMM(XNN_ARCH_ARM, xnn_f32_gemm_minmax_ukernel_1x16__neon_lane_ld128, 4, false, 1, 16, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM, xnn_f32_gemm_minmax_ukernel_6x16__neon_lane_ld128, 4, false, 6, 16, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM, xnn_f32_gemm_minmax_ukernel_4x8__neon_lane_ld128, 4, false, 4, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM, xnn_f32_gemm_minmax_ukernel_6x8__neon_lane_ld128, 4, false, 6, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM, xnn_f32_gemm_minmax_ukernel_1x8__neon_dup_ld64, 2, false, 1, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM, xnn_f32_gemm_minmax_ukernel_1x8__neon_lane_ld64, 2, false, 1, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM, xnn_f32_gemm_minmax_ukernel_1x8s4__neon, 4, false, 1, 8, 1, 4, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM, xnn_f32_gemm_minmax_ukernel_1x8s4__neonfma, 4, false, 1, 8, 1, 4, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM, xnn_f32_gemm_minmax_ukernel_4x8__neon_dup_ld128, 4, false, 4, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM, xnn_f32_gemm_minmax_ukernel_4x8__neon_lane_ld64, 2, false, 4, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM, xnn_f32_gemm_minmax_ukernel_4x8__neonfma_dup_ld64, 2, false, 4, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM, xnn_f32_gemm_minmax_ukernel_4x8s4__neon, 4, false, 4, 8, 1, 4, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM, xnn_f32_gemm_minmax_ukernel_5x8__neon_lane_ld64, 2, false, 5, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM, xnn_f32_gemm_minmax_ukernel_6x2__neon_lane_ld64, 2, false, 6, 2, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM, xnn_f32_gemm_minmax_ukernel_2x16__neon_lane_ld128, 4, false, 2, 16, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM, xnn_f32_gemm_minmax_ukernel_3x16__neon_lane_ld128, 4, false, 3, 16, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM, xnn_f32_gemm_minmax_ukernel_4x16__neon_lane_ld128, 4, false, 4, 16, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM, xnn_f32_gemm_minmax_ukernel_5x16__neon_lane_ld128, 4, false, 5, 16, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM, xnn_f32_gemm_minmax_ukernel_1x8__neon_lane_ld128, 4, false, 1, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM, xnn_f32_gemm_minmax_ukernel_1x8__neonfma_dup_ld64, 2, false, 1, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM, xnn_f32_gemm_minmax_ukernel_4x2__neon_lane_ld64, 2, false, 4, 2, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM, xnn_f32_gemm_minmax_ukernel_4x8__neon_dup_ld64, 2, false, 4, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM, xnn_f32_gemm_minmax_ukernel_4x8__neonfma_dup_ld128, 4, false, 4, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM, xnn_f32_gemm_minmax_ukernel_4x8s4__neonfma, 4, false, 4, 8, 1, 4, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM, xnn_f32_gemm_minmax_ukernel_6x8__neon_dup_ld128, 4, false, 6, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM, xnn_f32_gemm_minmax_ukernel_6x8__neon_lane_ld64, 2, false, 6, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM, xnn_f32_gemm_minmax_ukernel_6x8__neonfma_dup_ld64, 2, false, 6, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM, xnn_f32_gemm_minmax_ukernel_6x8__neonfma_dup_ld128, 4, false, 6, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM, xnn_f32_gemm_minmax_ukernel_6x8s4__neon, 4, false, 6, 8, 1, 4, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM, xnn_f32_gemm_minmax_ukernel_8x8s4__neon, 4, false, 8, 8, 1, 4, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
#endif  // XNN_ARCH_ARM || XNN_ARCH_ARM64

#if XNN_ARCH_ARM64
XNN_GEMM(XNN_ARCH_ARM64, xnn_f32_gemm_minmax_ukernel_2x16__aarch64_neonfma_lane_ld128, 4, false, 2, 16, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM64, xnn_f32_gemm_minmax_ukernel_3x16__aarch64_neonfma_lane_ld128, 4, false, 3, 16, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM64, xnn_f32_gemm_minmax_ukernel_6x16__aarch64_neonfma_lane_ld128, 4, false, 6, 16, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM64, xnn_f32_gemm_minmax_ukernel_4x8__aarch64_neonfma_lane_ld128, 4, false, 4, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM64, xnn_f32_gemm_minmax_ukernel_6x8__aarch64_neonfma_lane_ld128, 4, false, 6, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM64, xnn_f32_gemm_minmax_ukernel_1x8__aarch64_neonfma_lane_ld64, 2, false, 1, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM64, xnn_f32_gemm_minmax_ukernel_4x2__aarch64_neonfma_lane_ld64, 2, false, 4, 2, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM64, xnn_f32_gemm_minmax_ukernel_4x8__aarch64_neonfma_lane_ld64, 2, false, 4, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM64, xnn_f32_gemm_minmax_ukernel_5x8__aarch64_neonfma_lane_ld64, 2, false, 5, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM64, xnn_f32_gemm_minmax_ukernel_6x2__aarch64_neonfma_lane_ld64, 2, false, 6, 2, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM64, xnn_f32_gemm_minmax_ukernel_6x8__aarch64_neonfma_lane_ld64, 2, false, 6, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM64, xnn_f32_gemm_minmax_ukernel_6x8__neon_dup_ld64, 2, false, 6, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM64, xnn_f32_gemm_minmax_ukernel_6x8s4__neonfma, 4, false, 6, 8, 1, 4, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM64, xnn_f32_gemm_minmax_ukernel_8x8s4__neonfma, 4, false, 8, 8, 1, 4, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM64, xnn_f32_gemm_minmax_ukernel_1x16__aarch64_neonfma_lane_ld128, 4, false, 1, 16, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM64, xnn_f32_gemm_minmax_ukernel_4x16__aarch64_neonfma_lane_ld128, 4, false, 4, 16, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM64, xnn_f32_gemm_minmax_ukernel_5x16__aarch64_neonfma_lane_ld128, 4, false, 5, 16, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_ARM64, xnn_f32_gemm_minmax_ukernel_1x8__aarch64_neonfma_lane_ld128, 4, false, 1, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
#endif  // XNN_ARCH_ARM64

#if XNN_ARCH_X86 || XNN_ARCH_X86_64
XNN_GEMM(XNN_ARCH_X86, xnn_f32_gemm_minmax_ukernel_3x8__sse_dup, 4, false, 3, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_X86, xnn_f32_gemm_minmax_ukernel_3x8__sse_load1, 1, false, 3, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_X86, xnn_f32_gemm_minmax_ukernel_3x8s4__sse, 4, false, 3, 8, 1, 4, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_X86, xnn_f32_gemm_minmax_ukernel_4x8__sse_load1, 1, false, 4, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_X86, xnn_f32_gemm_minmax_ukernel_5x8__sse_dup, 4, false, 5, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_X86, xnn_f32_gemm_minmax_ukernel_5x8__sse_load1, 1, false, 5, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_X86, xnn_f32_gemm_minmax_ukernel_6x2c4__sse, 4, false, 6, 2, 4, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_X86, xnn_f32_gemm_minmax_ukernel_6x8__sse_dup, 4, false, 6, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_X86, xnn_f32_gemm_minmax_ukernel_6x8s4__sse, 4, false, 6, 8, 1, 4, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_X86, xnn_f32_gemm_minmax_ukernel_1x8__sse_dup, 4, false, 1, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_X86, xnn_f32_gemm_minmax_ukernel_1x8__sse_load1, 1, false, 1, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_X86, xnn_f32_gemm_minmax_ukernel_1x8s4__sse, 4, false, 1, 8, 1, 4, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_X86, xnn_f32_gemm_minmax_ukernel_4x2c4__sse, 4, false, 4, 2, 4, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_X86, xnn_f32_gemm_minmax_ukernel_4x8__sse_dup, 4, false, 4, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_X86, xnn_f32_gemm_minmax_ukernel_4x8s4__sse, 4, false, 4, 8, 1, 4, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_X86, xnn_f32_gemm_minmax_ukernel_5x8s4__sse, 4, false, 5, 8, 1, 4, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_X86, xnn_f32_gemm_minmax_ukernel_6x8__sse_load1, 1, false, 6, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_avx, xnn_f32_gemm_minmax_ukernel_1x8__avx_broadcast, 1, false, 1, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_avx, xnn_f32_gemm_minmax_ukernel_3x16__avx_broadcast, 1, false, 3, 16, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_avx, xnn_f32_gemm_minmax_ukernel_5x8__avx_broadcast, 1, false, 5, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_avx, xnn_f32_gemm_minmax_ukernel_6x8__avx_broadcast, 1, false, 6, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_avx, xnn_f32_gemm_minmax_ukernel_6x16__avx_broadcast, 1, false, 6, 16, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_avx, xnn_f32_gemm_minmax_ukernel_1x16__avx_broadcast, 1, false, 1, 16, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_avx, xnn_f32_gemm_minmax_ukernel_4x8__avx_broadcast, 1, false, 4, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_avx, xnn_f32_gemm_minmax_ukernel_4x16__avx_broadcast, 1, false, 4, 16, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_avx, xnn_f32_gemm_minmax_ukernel_5x16__avx_broadcast, 1, false, 5, 16, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_avx, xnn_f32_gemm_minmax_ukernel_7x8__avx_broadcast, 1, false, 7, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_fma3, xnn_f32_gemm_minmax_ukernel_1x8__fma3_broadcast, 1, false, 1, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_fma3, xnn_f32_gemm_minmax_ukernel_1x16__fma3_broadcast, 1, false, 1, 16, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_fma3, xnn_f32_gemm_minmax_ukernel_3x16__fma3_broadcast, 1, false, 3, 16, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_fma3, xnn_f32_gemm_minmax_ukernel_4x8__fma3_broadcast, 1, false, 4, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_fma3, xnn_f32_gemm_minmax_ukernel_5x8__fma3_broadcast, 1, false, 5, 8, , 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_fma3, xnn_f32_gemm_minmax_ukernel_1x16s4__fma3_broadcast, 4, false, 1, 16, 1, 4, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_fma3, xnn_f32_gemm_minmax_ukernel_3x16s4__fma3_broadcast, 4, false, 3, 16, 1, 4, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_fma3, xnn_f32_gemm_minmax_ukernel_4x16__fma3_broadcast, 1, false, 4, 16, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_fma3, xnn_f32_gemm_minmax_ukernel_4x16s4__fma3_broadcast, 4, false, 4, 16, 1, 4, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_fma3, xnn_f32_gemm_minmax_ukernel_5x16__fma3_broadcast, 1, false, 5, 16, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_fma3, xnn_f32_gemm_minmax_ukernel_5x16s4__fma3_broadcast, 4, false, 5, 16, 1, 4, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_fma3, xnn_f32_gemm_minmax_ukernel_6x8__fma3_broadcast, 1, false, 6, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_fma3, xnn_f32_gemm_minmax_ukernel_6x16__fma3_broadcast, 1, false, 6, 16, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_fma3, xnn_f32_gemm_minmax_ukernel_6x16s4__fma3_broadcast, 4, false, 6, 16, 1, 4, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_fma3, xnn_f32_gemm_minmax_ukernel_7x8__fma3_broadcast, 1, false, 7, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_fma3, xnn_f32_gemm_minmax_ukernel_8x8__fma3_broadcast, 1, false, 8, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
#endif  // XNN_ARCH_X86 || XNN_ARCH_X86_64

#if XNN_ENABLE_AVX512F && (XNN_ARCH_X86 || XNN_ARCH_X86_64)
XNN_GEMM(xnn_arch_x86_avx512f, xnn_f32_gemm_minmax_ukernel_1x16__avx512f_broadcast, 1, false, 1, 16, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_avx512f, xnn_f32_gemm_minmax_ukernel_6x16__avx512f_broadcast, 1, false, 6, 16, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_avx512f, xnn_f32_gemm_minmax_ukernel_7x16__avx512f_broadcast, 1, false, 7, 16, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_avx512f, xnn_f32_gemm_minmax_ukernel_8x16__avx512f_broadcast, 1, false, 8, 16, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_avx512f, xnn_f32_gemm_minmax_ukernel_9x16__avx512f_broadcast, 1, false, 9, 16, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_avx512f, xnn_f32_gemm_minmax_ukernel_10x16__avx512f_broadcast, 1, false, 10, 16, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_avx512f, xnn_f32_gemm_minmax_ukernel_11x16__avx512f_broadcast, 1, false, 11, 16, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_avx512f, xnn_f32_gemm_minmax_ukernel_16x16__avx512f_broadcast, 1, false, 16, 16, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_avx512f, xnn_f32_gemm_minmax_ukernel_1x32__avx512f_broadcast, 1, false, 1, 32, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_avx512f, xnn_f32_gemm_minmax_ukernel_6x32__avx512f_broadcast, 1, false, 6, 32, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_avx512f, xnn_f32_gemm_minmax_ukernel_7x32__avx512f_broadcast, 1, false, 7, 32, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_avx512f, xnn_f32_gemm_minmax_ukernel_8x32__avx512f_broadcast, 1, false, 8, 32, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_avx512f, xnn_f32_gemm_minmax_ukernel_9x32__avx512f_broadcast, 1, false, 9, 32, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_avx512f, xnn_f32_gemm_minmax_ukernel_10x32__avx512f_broadcast, 1, false, 10, 32, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_avx512f, xnn_f32_gemm_minmax_ukernel_11x32__avx512f_broadcast, 1, false, 11, 32, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_avx512f, xnn_f32_gemm_minmax_ukernel_16x32__avx512f_broadcast, 1, false, 16, 32, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_avx512f, xnn_f32_gemm_minmax_ukernel_1x64__avx512f_broadcast, 1, false, 1, 64, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_avx512f, xnn_f32_gemm_minmax_ukernel_6x64__avx512f_broadcast, 1, false, 6, 64, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_avx512f, xnn_f32_gemm_minmax_ukernel_7x64__avx512f_broadcast, 1, false, 7, 64, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_avx512f, xnn_f32_gemm_minmax_ukernel_8x64__avx512f_broadcast, 1, false, 8, 64, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_avx512f, xnn_f32_gemm_minmax_ukernel_9x64__avx512f_broadcast, 1, false, 9, 64, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_avx512f, xnn_f32_gemm_minmax_ukernel_10x64__avx512f_broadcast, 1, false, 10, 64, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_avx512f, xnn_f32_gemm_minmax_ukernel_11x64__avx512f_broadcast, 1, false, 11, 64, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_avx512f, xnn_f32_gemm_minmax_ukernel_16x64__avx512f_broadcast, 1, false, 16, 64, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_avx512f, xnn_f32_gemm_minmax_ukernel_4x16__avx512f_broadcast, 1, false, 4, 16, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_avx512f, xnn_f32_gemm_minmax_ukernel_5x16__avx512f_broadcast, 1, false, 5, 16, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_avx512f, xnn_f32_gemm_minmax_ukernel_12x16__avx512f_broadcast, 1, false, 12, 16, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_avx512f, xnn_f32_gemm_minmax_ukernel_13x16__avx512f_broadcast, 1, false, 13, 16, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_avx512f, xnn_f32_gemm_minmax_ukernel_14x16__avx512f_broadcast, 1, false, 14, 16, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_avx512f, xnn_f32_gemm_minmax_ukernel_15x16__avx512f_broadcast, 1, false, 15, 16, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_avx512f, xnn_f32_gemm_minmax_ukernel_4x32__avx512f_broadcast, 1, false, 4, 32, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_avx512f, xnn_f32_gemm_minmax_ukernel_5x32__avx512f_broadcast, 1, false, 5, 32, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_avx512f, xnn_f32_gemm_minmax_ukernel_12x32__avx512f_broadcast, 1, false, 12, 32, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_avx512f, xnn_f32_gemm_minmax_ukernel_13x32__avx512f_broadcast, 1, false, 13, 32, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_avx512f, xnn_f32_gemm_minmax_ukernel_14x32__avx512f_broadcast, 1, false, 14, 32, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_avx512f, xnn_f32_gemm_minmax_ukernel_15x32__avx512f_broadcast, 1, false, 15, 32, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_avx512f, xnn_f32_gemm_minmax_ukernel_4x64__avx512f_broadcast, 1, false, 4, 64, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_avx512f, xnn_f32_gemm_minmax_ukernel_5x64__avx512f_broadcast, 1, false, 5, 64, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_avx512f, xnn_f32_gemm_minmax_ukernel_12x64__avx512f_broadcast, 1, false, 12, 64, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_avx512f, xnn_f32_gemm_minmax_ukernel_13x64__avx512f_broadcast, 1, false, 13, 64, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_avx512f, xnn_f32_gemm_minmax_ukernel_14x64__avx512f_broadcast, 1, false, 14, 64, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(xnn_arch_x86_avx512f, xnn_f32_gemm_minmax_ukernel_15x64__avx512f_broadcast, 1, false, 15, 64, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
#endif  // XNN_ENABLE_AVX512F && (XNN_ARCH_X86 || XNN_ARCH_X86_64)

#if XNN_ARCH_WASMSIMD || XNN_ARCH_WASMRELAXEDSIMD
XNN_GEMM(XNN_ARCH_WASMSIMD, xnn_f32_gemm_minmax_ukernel_1x8__wasmsimd_arm_splat, 4, false, 1, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASMSIMD, xnn_f32_gemm_minmax_ukernel_1x8__wasmsimd_x86_loadsplat, 1, false, 1, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASMSIMD, xnn_f32_gemm_minmax_ukernel_1x8__wasmsimd_x86_splat, 4, false, 1, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASMSIMD, xnn_f32_gemm_minmax_ukernel_3x8__wasmsimd_x86_loadsplat, 1, false, 3, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASMSIMD, xnn_f32_gemm_minmax_ukernel_3x8s4__wasmsimd_arm, 4, false, 3, 8, 1, 4, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASMSIMD, xnn_f32_gemm_minmax_ukernel_3x8s4__wasmsimd_x86, 4, false, 3, 8, 1, 4, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASMSIMD, xnn_f32_gemm_minmax_ukernel_4x2c4__wasmsimd_arm, 4, false, 4, 2, 4, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASMSIMD, xnn_f32_gemm_minmax_ukernel_4x2c4__wasmsimd_x86, 4, false, 4, 2, 4, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASMSIMD, xnn_f32_gemm_minmax_ukernel_4x8__wasmsimd_x86_loadsplat, 1, false, 4, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASMSIMD, xnn_f32_gemm_minmax_ukernel_5x8__wasmsimd_arm_loadsplat, 1, false, 5, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASMSIMD, xnn_f32_gemm_minmax_ukernel_6x8__wasmsimd_arm_splat, 4, false, 6, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASMSIMD, xnn_f32_gemm_minmax_ukernel_6x8__wasmsimd_x86_loadsplat, 1, false, 6, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASMSIMD, xnn_f32_gemm_minmax_ukernel_6x8__wasmsimd_x86_splat, 4, false, 6, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASMSIMD, xnn_f32_gemm_minmax_ukernel_6x8s4__wasmsimd_arm, 4, false, 6, 8, 1, 4, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASMSIMD, xnn_f32_gemm_minmax_ukernel_6x8s4__wasmsimd_x86, 4, false, 6, 8, 1, 4, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASMSIMD, xnn_f32_gemm_minmax_ukernel_1x8__wasmsimd_arm_loadsplat, 1, false, 1, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASMSIMD, xnn_f32_gemm_minmax_ukernel_1x8s4__wasmsimd_arm, 4, false, 1, 8, 1, 4, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASMSIMD, xnn_f32_gemm_minmax_ukernel_1x8s4__wasmsimd_x86, 4, false, 1, 8, 1, 4, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASMSIMD, xnn_f32_gemm_minmax_ukernel_3x8__wasmsimd_arm_loadsplat, 1, false, 3, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASMSIMD, xnn_f32_gemm_minmax_ukernel_3x8__wasmsimd_arm_splat, 4, false, 3, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASMSIMD, xnn_f32_gemm_minmax_ukernel_3x8__wasmsimd_x86_splat, 4, false, 3, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASMSIMD, xnn_f32_gemm_minmax_ukernel_4x8__wasmsimd_arm_loadsplat, 1, false, 4, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASMSIMD, xnn_f32_gemm_minmax_ukernel_4x8__wasmsimd_arm_splat, 4, false, 4, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASMSIMD, xnn_f32_gemm_minmax_ukernel_4x8__wasmsimd_x86_splat, 4, false, 4, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASMSIMD, xnn_f32_gemm_minmax_ukernel_4x8s4__wasmsimd_arm, 4, false, 4, 8, 1, 4, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASMSIMD, xnn_f32_gemm_minmax_ukernel_4x8s4__wasmsimd_x86, 4, false, 4, 8, 1, 4, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASMSIMD, xnn_f32_gemm_minmax_ukernel_5x8__wasmsimd_arm_splat, 4, false, 5, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASMSIMD, xnn_f32_gemm_minmax_ukernel_5x8__wasmsimd_x86_loadsplat, 1, false, 5, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASMSIMD, xnn_f32_gemm_minmax_ukernel_5x8__wasmsimd_x86_splat, 4, false, 5, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASMSIMD, xnn_f32_gemm_minmax_ukernel_5x8s4__wasmsimd_arm, 4, false, 5, 8, 1, 4, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASMSIMD, xnn_f32_gemm_minmax_ukernel_5x8s4__wasmsimd_x86, 4, false, 5, 8, 1, 4, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASMSIMD, xnn_f32_gemm_minmax_ukernel_6x8__wasmsimd_arm_loadsplat, 1, false, 6, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
#endif  // XNN_ARCH_WASMSIMD || XNN_ARCH_WASMRELAXEDSIMD

#if XNN_ARCH_WASMRELAXEDSIMD
XNN_GEMM(XNN_ARCH_WASMRELAXEDSIMD, xnn_f32_gemm_minmax_ukernel_1x8__wasmrelaxedsimd_loadsplat, 1, false, 1, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASMRELAXEDSIMD, xnn_f32_gemm_minmax_ukernel_3x8__wasmrelaxedsimd_loadsplat, 1, false, 3, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASMRELAXEDSIMD, xnn_f32_gemm_minmax_ukernel_3x8__wasmrelaxedsimd_splat, 4, false, 3, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASMRELAXEDSIMD, xnn_f32_gemm_minmax_ukernel_3x8s4__wasmrelaxedsimd_fma, 4, false, 3, 8, 1, 4, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASMRELAXEDSIMD, xnn_f32_gemm_minmax_ukernel_4x8__wasmrelaxedsimd_loadsplat, 1, false, 4, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASMRELAXEDSIMD, xnn_f32_gemm_minmax_ukernel_4x8__wasmrelaxedsimd_splat, 4, false, 4, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASMRELAXEDSIMD, xnn_f32_gemm_minmax_ukernel_4x8s4__wasmrelaxedsimd_fma, 4, false, 4, 8, 1, 4, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASMRELAXEDSIMD, xnn_f32_gemm_minmax_ukernel_5x8__wasmrelaxedsimd_loadsplat, 1, false, 5, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASMRELAXEDSIMD, xnn_f32_gemm_minmax_ukernel_6x8__wasmrelaxedsimd_loadsplat, 1, false, 6, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASMRELAXEDSIMD, xnn_f32_gemm_minmax_ukernel_1x8__wasmrelaxedsimd_fma_loadsplat, 1, false, 1, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASMRELAXEDSIMD, xnn_f32_gemm_minmax_ukernel_1x8__wasmrelaxedsimd_fma_splat, 4, false, 1, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASMRELAXEDSIMD, xnn_f32_gemm_minmax_ukernel_1x8__wasmrelaxedsimd_splat, 4, false, 1, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASMRELAXEDSIMD, xnn_f32_gemm_minmax_ukernel_1x8s4__wasmrelaxedsimd, 4, false, 1, 8, 1, 4, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASMRELAXEDSIMD, xnn_f32_gemm_minmax_ukernel_1x8s4__wasmrelaxedsimd_fma, 4, false, 1, 8, 1, 4, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASMRELAXEDSIMD, xnn_f32_gemm_minmax_ukernel_3x8__wasmrelaxedsimd_fma_loadsplat, 1, false, 3, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASMRELAXEDSIMD, xnn_f32_gemm_minmax_ukernel_3x8__wasmrelaxedsimd_fma_splat, 4, false, 3, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASMRELAXEDSIMD, xnn_f32_gemm_minmax_ukernel_3x8s4__wasmrelaxedsimd, 4, false, 3, 8, 1, 4, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASMRELAXEDSIMD, xnn_f32_gemm_minmax_ukernel_4x2c4__wasmrelaxedsimd, 4, false, 4, 2, 4, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASMRELAXEDSIMD, xnn_f32_gemm_minmax_ukernel_4x2c4__wasmrelaxedsimd_fma, 4, false, 4, 2, 4, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASMRELAXEDSIMD, xnn_f32_gemm_minmax_ukernel_4x8__wasmrelaxedsimd_fma_loadsplat, 1, false, 4, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASMRELAXEDSIMD, xnn_f32_gemm_minmax_ukernel_4x8__wasmrelaxedsimd_fma_splat, 4, false, 4, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASMRELAXEDSIMD, xnn_f32_gemm_minmax_ukernel_4x8s4__wasmrelaxedsimd, 4, false, 4, 8, 1, 4, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASMRELAXEDSIMD, xnn_f32_gemm_minmax_ukernel_5x8__wasmrelaxedsimd_fma_loadsplat, 1, 5, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASMRELAXEDSIMD, xnn_f32_gemm_minmax_ukernel_5x8__wasmrelaxedsimd_fma_splat, 4, false, 5, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASMRELAXEDSIMD, xnn_f32_gemm_minmax_ukernel_5x8__wasmrelaxedsimd_splat, 4, false, 5, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASMRELAXEDSIMD, xnn_f32_gemm_minmax_ukernel_5x8s4__wasmrelaxedsimd, 4, false, 5, 8, 1, 4, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASMRELAXEDSIMD, xnn_f32_gemm_minmax_ukernel_5x8s4__wasmrelaxedsimd_fma, 4, false, 5, 8, 1, 4, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASMRELAXEDSIMD, xnn_f32_gemm_minmax_ukernel_6x8__wasmrelaxedsimd_fma_loadsplat, 1, false, 6, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASMRELAXEDSIMD, xnn_f32_gemm_minmax_ukernel_6x8__wasmrelaxedsimd_fma_splat, 4, false, 6, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASMRELAXEDSIMD, xnn_f32_gemm_minmax_ukernel_6x8__wasmrelaxedsimd_splat, 4, false, 6, 8, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASMRELAXEDSIMD, xnn_f32_gemm_minmax_ukernel_6x8s4__wasmrelaxedsimd, 4, false, 6, 8, 1, 4, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASMRELAXEDSIMD, xnn_f32_gemm_minmax_ukernel_6x8s4__wasmrelaxedsimd_fma, 4, false, 6, 8, 1, 4, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
#endif  // XNN_ARCH_WASMRELAXEDSIMD

#if XNN_ARCH_WASM || XNN_ARCH_WASMSIMD || XNN_ARCH_WASMRELAXEDSIMD
XNN_GEMM(XNN_ARCH_WASM, xnn_f32_gemm_minmax_ukernel_2x4__wasm, 1, false, 2, 4, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASM, xnn_f32_gemm_minmax_ukernel_4x2__wasm, 1, false, 4, 2, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASM, xnn_f32_gemm_minmax_ukernel_4x4__wasm, 1, false, 4, 4, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_WASM, xnn_f32_gemm_minmax_ukernel_1x4__wasm, 1, false, 1, 4, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
#endif  // XNN_ARCH_WASM || XNN_ARCH_WASMSIMD || XNN_ARCH_WASMRELAXEDSIMD

// SCALAR
XNN_GEMM(0, xnn_f32_gemm_minmax_ukernel_1x4__scalar, 1, false, 1, 4, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(0, xnn_f32_gemm_minmax_ukernel_4x2__scalar, 1, false, 4, 2, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(0, xnn_f32_gemm_minmax_ukernel_4x4__scalar, 1, false, 4, 4, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(0, xnn_f32_gemm_minmax_ukernel_2x4__scalar, 1, false, 2, 4, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)

#if XNN_ENABLE_RISCV_VECTOR && XNN_ARCH_RISCV
XNN_GEMM(XNN_ARCH_RISCV, xnn_f32_gemm_minmax_ukernel_1x4v__rvv, 1, false, 1, 4, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_RISCV, xnn_f32_gemm_minmax_ukernel_7x4v__rvv, 1, false, 7, 4, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
#endif  // XNN_ENABLE_RISCV_VECTOR && XNN_ARCH_RISCV

#if XNN_ENABLE_HVX && XNN_ARCH_HEXAGON
XNN_GEMM(XNN_ARCH_HEXAGON, xnn_f32_gemm_minmax_ukernel_1x128__hvx_broadcast, 1, false, 1, 128, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_HEXAGON, xnn_f32_gemm_minmax_ukernel_2x128__hvx_broadcast, 1, false, 2, 128, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_HEXAGON, xnn_f32_gemm_minmax_ukernel_7x64__hvx_broadcast, 1, false, 7, 64, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_HEXAGON, xnn_f32_gemm_minmax_ukernel_8x32__hvx_broadcast, 1, false, 8, 32, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_HEXAGON, xnn_f32_gemm_minmax_ukernel_16x32__hvx_broadcast, 1, false, 16, 32, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_HEXAGON, xnn_f32_gemm_minmax_ukernel_1x32__hvx_broadcast, 1, false, 1, 32, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_HEXAGON, xnn_f32_gemm_minmax_ukernel_1x64__hvx_broadcast, 1, false, 1, 64, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
XNN_GEMM(XNN_ARCH_HEXAGON, xnn_f32_gemm_minmax_ukernel_4x64__hvx_broadcast, 1, 4, 64, 1, 1, false, float, struct xnn_f32_minmax_params , xnn_init_f32_minmax_scalar_params, xnn_pack_f32_gemm_goi_w)
#endif  // XNN_ENABLE_HVX && XNN_ARCH_HEXAGON
